on:
  workflow_call:
    inputs:
      use_poetry:
        required: false
        type: boolean
      use_sphinx:
        required: false
        type: boolean
      python_version:
        required: false
        type: string
        default: '3.11'
      platform:
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      PYPI_TOKEN:
        required: true
jobs:
  build:
    if: ${{ inputs.use_cibuildwheel }} == 'false'
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        if: ${{ inputs.use_poetry }} == 'true'
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          if [ "${{ inputs.use_poetry }}" = "true" ]; then
            poetry install --all-extras
          else
            pip install -r requirements.txt
            if [ -f requirements-dev.txt ]; then
              pip install -r requirements-dev.txt
            fi
          fi

      - name: Building documentation
        if: ${{ inputs.use_sphinx }} == 'true'
        run: |
          if [ "${{ inputs.use_poetry }}" = "true" ]; then
            cd docs && poetry run make clean html
          else
            cd docs && make clean html
          fi

      - name: Publishing documentation
        if: ${{ inputs.use_sphinx }} == 'true'
        run: |
            if [ "${{ inputs.use_poetry }}" = "true" ]; then
                poetry run ghp-import -f -n -p docs/_build/html
            else
                gh-pages -d docs/_build
            fi

      - name: Push to PyPi
        run: |
          if [ "${{ inputs.use_poetry }}" = "true" ]; then
            poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
            poetry publish --build
          else
            python setup.py sdist bdist_wheel
            twine upload dist/*
          fi